function(funcdoodle_apply_build_config target)
	target_compile_definitions(${target} PRIVATE IMGUI_ENABLE_TEST_ENGINE IMGUI_TEST_ENGINE_ENABLE_COROUTINE_STDTHREAD_IMPL=1)

	if(CMAKE_BUILD_TYPE STREQUAL "Debug")
		target_compile_definitions(${target} PRIVATE DEBUG)
		if(UNIX AND NOT APPLE AND ISTILING)
			target_compile_definitions(${target} PRIVATE TILING)
		endif()
		if(NOT WIN32)
			target_compile_options(${target} PRIVATE -g -gdwarf-4 -fsanitize=address -fno-omit-frame-pointer)
			target_link_options(${target} PRIVATE -fsanitize=address)
		endif()
	elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
		if(UNIX AND NOT APPLE AND ISTILING)
			target_compile_definitions(${target} PRIVATE TILING)
		endif()
		target_compile_definitions(${target} PRIVATE NDEBUG)
		target_compile_options(${target} PRIVATE -O3)
	endif()

	if(APPLE)
		target_compile_definitions(${target} PRIVATE MACOS)
	endif()
endfunction()
