name: Deploy Doxygen Docs

on:
push:
branches: [ "master" ]
workflow_dispatch:

permissions:
contents: read
pages: write
id-token: write

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout repo
    uses: actions/checkout@v4

  - name: Install dependencies
    run: |
      sudo apt update
      sudo apt install -y doxygen graphviz

  - name: Generate docs
    run: |
      chmod +x ./scripts/docs.sh
      ./scripts/docs.sh

  - name: Upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: ./doxy

  - name: Deploy to GitHub Pages
    uses: actions/deploy-pages@v4
